Artigo jeffotoni => primeiros passos Go
OsProgramadores/op-website-hugo pull request #509
Opened 2020-12-23 04:39 UTC by jeffotoni

2021-01-11 01:49 UTC, mpinheir requested changes
Muito obrigado pela contribuição e perdão pela demora da revisão. Vide por favor as mudanças necessárias e sugeridas para melhorar o artigo antes que possamos postar no site. Desde já muito obrigado.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +
remover o a entre para e os

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Nasce uma nova linguagem Go, para atender as novas necessidades e resolver problemas aproveitando o máximo possível do poder computacional. E é claro criando o seu mascote para a os milhares de gophe
retirar o a entre viram e surgir na última linha do último parágrafo.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Para iniciarmos em Go vamos dar alguns passos para trás, vamos começar toda nossa trajetória conhecendo o site oficial da lang esta é a página oficial golang.org, aqui encontraremos todas informações
Mude por favor para: Para iniciarmos em Go vamos dar alguns passos para trás, vamos começar toda nossa trajetória conhecendo o site oficial da linguagem:  golang.org. Nesta página encontraremos informações sobre Go e muito mais. Nesta página temos os docs, packages, blog e o play.golang.org, specificações da lingugem, download, tour em Go e muito mais.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Antes de instalar Go, ou rodar Go pelo play, vamos da uma passada em algumas partes do doc para que possamos entender um pouco da história do Go e por que nasceu uma nova linguagem neste universo de
vamos dar ao invés de vamos da

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +[Effective Go](https://golang.org/doc/effective_go.html#introduction) ❤️ neste site está todo material que precisa para ter uma boa noção da linguagem Go: Estrutura de controle, funções, Programação
todo material que se precisa ao invés de que precisa.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +[Tour Go](https://tour.golang.org/welcome/1) ❤️ neste site você irá conseguir testar e da uma passada em algumas das funcionalidades da linguagem Go 😱 isto mesmo tudo pelo browser sem precisar instal
dar ao invés de da

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Aqui é muito lindo, você não precisa instalar nadinha na máquina para executar algo rapidamente em Go, basta entrar no play.golang.org
Sugiro mudar para:
No  [Play Go](https://play.golang.org/p/MAohLsrz7JQ) você irá conseguir executar Go 😱 sem instlaar nada nada. Todo o código Go é escrito e executado no navegador (browser) e simplificando muito assim o aprendizado.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este link seria o nosso terceiro passo, acredito que agora tem diversas dúvidas, geradas pelo Effective Go e pelo Tour que fez.
Mude por favor para: Este link seria o nosso terceiro passo e acredito que agora você tnha diversas dúvidas, geradas pelo Effective Go e pelo Tour que fez.

[Faq](https://golang.org/doc/faq) ❤️ é aqui que irá você tirar algumas dúvidas. Esta página é essencial para organizar suas ideias e entender realmente um pouco mais sobre Go🥰. O tempo gasto lendo esta página irá com certeza lhe ajudar a economizar horas de trabalho.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este link seria para que possa da uma passada e entender como são organizados e como é a documentação das funções, libs, pkgs que possamoms utilizar na linguagem Go. Este é um dos pontos fortes da li
Mude por favor para: Este link contem documentação para ajudar você  a entender como são organizados funções, libs, pkgs que podem ser usados na linguagem Go.
[Pkgs](https://golang.org/pkg/) ❤️ escolhi aqui o [pkg string](https://golang.org/pkg/strings) que inclui exemplos que podem  ser executados diretamente no navegador  facilitar o aprendizado e entendimento🥰.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este link é sobre as IDEs e Editores que poderá utilizar quando tiver Godando. A linguagem Go não precisa de muito para que possamos editar nossos códigos, mas temos alguns plugins interessantes para
Por favor: Mude Godando para escrevendo programas em Go.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Isto torno-se ao longo dos anos algo tão padrão para quem está desenvolvendo no universo Go que soa como poesia para os ouvidos. Sabemos que go é uma tentativa de juntar dois mundos distintos, o mund
tornou-se ao invés de torno-se

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Isto torno-se ao longo dos anos algo tão padrão para quem está desenvolvendo no universo Go que soa como poesia para os ouvidos. Sabemos que go é uma tentativa de juntar dois mundos distintos, o mund
Sugiro remover este parágrafo pois ficou bem confuso.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Em Go temos algumas características marcantes da linguagem que torna ela ainda mais poderosa para desenvolvimento de aplicações web para servidores.
Sugiro mudar para: Em Go temos algumas características marcantes da linguagem que a tornam  ainda mais poderosa para desenvolvimento de aplicações web para servidores.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> + - Multiplataformas agora com suporte a RISC-V
Multiplataforma (singular)

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Todos estes pontos torna a linguagem ainda mais interessante, a equipe de engenheiros que desenvolveu a linguagem fizeram um excelente trabalho ou melhor veem fazendo, Go é simplesmente fantástico al
Mude por favor este parágrafo para explicar os benefícios dos items que você listou acima.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este é o momento que todos esperávamos, colocar a mão na massa e instalar local, no site oficial não tem como errar, não tem nada mais simples que instalar o Go em sua máquina para que possa programa
Remova por favor este parágrafo e foque por favor na instalação do Go na máquina do usuário. Acho que isso vai simplificar o artigo e o processo que pode parecer simples para você mas é complexo para as pessoas que sequer sabem o que é um IDE.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Sabendo de tudo isto vamos a instalação de Go e vamos ver o tão quanto ela é complexa 😜😜, brincadeirinha… 😂
Sugiro remover este parágrafo.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +4. Para deixar o que fizemos acima global, ou seja toda vez que for entrar em seu terminal "go" seja executado você pode fazer isso adicionando a seguinte linha que mostrei acima ao seu $HOME/.profil
Ajuste por favor pois está confuso de ler.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Agora sim chegou a hora de nossos primeiros **"hello world"** utilizando Go.
primeiro ao invés de primeiros

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Não tem segredo, podemos utilizar de qualquer editor que vimos acima e irmos para cima. Em Go não precisamos compilar quando estamos godando podemos simplesmente executar nossos programas sem precisa
Mude por favor para:
Não tem segredo, podemos utilizar de qualquer editor que listado acima. Em Go podemos simplesmente executar nossos programas sem precisar transforma-los em binários ou seja compilar.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Abaixo está nosso primeiro hello world, e basta salvar o arquivo com a extensão "_.go_", coloque o nome de "_main.go_" depois basta executar ele com o comando "_go run main.go_", em nosso exemplo cha
Você tem certeza que o go run não compila e executa o código?

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este nosso hello world é a menor estrutura que podemos montar para da saída no terminal, sem usar pacote.
para dar ao invés de para da

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este outro exemplo vamos utilizar um pacote nativo Go.
Neste outro exemplo...

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Para ficar um pouquinha mais claro quando usarmos a função println temos que saber que que ela é uma função embutida (no tempo de execução) que pode eventualmente ser removida, enquanto o "_fmt_" pac
Um pouquinho ao invés de pouqinha

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Para ficar um pouquinha mais claro quando usarmos a função println temos que saber que que ela é uma função embutida (no tempo de execução) que pode eventualmente ser removida, enquanto o "_fmt_" pac
remover a duplicação de que.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Para ficar um pouquinha mais claro quando usarmos a função println temos que saber que que ela é uma função embutida (no tempo de execução) que pode eventualmente ser removida, enquanto o "_fmt_" pac
Acho que seria importante explicar mais sobre esta parte. O que é o _fm_ por exemplo?

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Agora vamos transformar em **binário** vamos compilar e para isto vamos utilizar o "go build" ou "GOARCH=386 GOOS=linux go build" estamos agora informando a arquitetura e sistema operacional que dese
para o qual desejamos ao invés de que desejamos.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Este comando irá fazer o **build** ele irá gerar um "_executável_" um binário para ser executado em seu sistema operacional. Muito fácil não é? 😍 Eu diria muito **lindo**. Com este binário você irá c
Mude por favor para:
Este comando irá fazer o **build** e será gerado um "_executável_", também conhecido como binário, para ser executado em seu sistema operacional. Muito fácil não é? 😍 Eu diria muito **lindo**. Com este binário você irá conseguir executar o progrrama em sua máquina ou em qualquer servidor que tenha a mesma **arquitetura e sistema operacional. O mais legal é que é gerado um **binário estatico** que não  contém dependências para instalar em seu servidor. Legal não é? Para sabermos se o arquivo binário é dinâmico ou estático basta rodarmos o seguinte commando:

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Se aparecer esta saída bingo, é um executável estático sem dependências.
Se aparecer esta saída entao o executável gerado é  estático sem dependências.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +Se aparecer esta saída bingo, é um executável estático sem dependências.
Assumindo que o sistema está configurado para uso do idioma Português.

2021-01-11 01:49 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +É importante frisar sempre este detalhe: **"Não instalamos nada de Go em nossos servidores Web"** é exatamente o que leu, só precisa do binário. ❤️ Foi devido a isto que Go ficou conhecido por ser a
É importante frisar sempre este detalhe: **"Não instalamos nada de Go em nossos servidores Web"** é exatamente o que leu, só precisa do binário. ❤️ Foi devido a isto que Go ficou conhecido por ser a Linguagem dos Containers. Diz que isto não é fantástico ? 😍 Para rodar  uma aplicação Web em seu servidor, basta enviar o binário para ele. Uau, isto mesmo, somente do binário e sem precisar instalar mais nada referente ao seu projeto, nadinha.

2021-01-12 00:45 UTC, mpinheir commented on content/blog/primeiros-passos-go.md
> +A linguagem Go em seu universo de possibilidades é uma linguagem de uso comum não gosto muito deste termo fica parecendo que ela é tipo uma bala de prata e resolve todos os problemas mas que na verda
@jeffotoni acho que você esqueceu desta mudança.

2021-01-22 04:43 UTC, mpinheir approved these changes
Vou publicar e depois dar uma revisada no editor no computador pois vai ser mais fácil do que editar no GitHub. Mais uma vez obrigado pela contribuição.

2021-01-22 04:43 UTC, merged

2021-01-22 12:22 UTC, jeffotoni commented
Vi que precisa fazer outras correções depois que publicou, imagem não encontrou, tamanho de imagem, espaçamentos, vou corrigir e enviar novamente.