Update PARTICIPANTES.md
OsProgramadores/op-website-hugo pull request #548
Opened 2021-04-27 02:16 UTC by vieirajunior-90

2021-04-27 03:05 UTC, marcopaganini requested changes
Duas coisas:

1) Voce tem que alinhar as barras verticais. No seu caso, a última barra está desalinhada.

2) Voce modificou a ultima linha. Provavelmente o seu editor removeu ou adicionou um ENTER no final da linha.

2021-04-27 11:36 UTC, vieirajunior-90 commented
Ok, vou verificar.

2021-04-27 12:58 UTC, vieirajunior-90 commented
Marco, na primeira vez consegui enviar tranquilamente, porém agora na hora de enviar, aparece o seguinte erro:

error: src refspec desafio does not match any
error: failed to push some refs to 'https://github.com/OsProgramadores/op-website-hugo.git'

2021-04-28 05:10 UTC, marcopaganini approved these changes

2021-04-28 05:11 UTC, merged