Podcast menu change/folder structure revamp.
OsProgramadores/op-website-hugo pull request #657
Opened 2021-12-29 03:17 UTC by mpinheir

Changed Menu option from **Podcasts** to **Podcast** (singular) and adjusted overall Podcast folder structure.

2021-12-29 04:20 UTC, marcopaganini requested changes

2021-12-29 04:20 UTC, marcopaganini commented on layouts/_default/podcast.html
> +<!DOCTYPE html>
Arquivo novo? Deveria ser um `git mv podcasts.html podcast.html`, correto? Foi isso ou criou um outro?

2021-12-29 05:11 UTC, mpinheir commented on layouts/_default/podcast.html
> +<!DOCTYPE html>
dei um rename.

2021-12-29 20:13 UTC, marcopaganini requested changes

2021-12-29 20:13 UTC, marcopaganini commented on layouts/_default/podcast.html
> +<!DOCTYPE html>
Faltou o push?

2021-12-30 04:42 UTC, marcopaganini approved these changes

2021-12-30 04:42 UTC, merged