Revamped site layout to improve overall user experience.
OsProgramadores/op-website-hugo pull request #705
Opened 2022-07-17 17:30 UTC by mpinheir

2022-07-17 19:30 UTC, marcopaganini requested changes
Além dos comentários nos arquivos, eu notei que foram adicionados vários arquivos grandes (PNG), com mais de 1MB cada. Vários tem versões "converted" que são menores. Talvez renomear as versões "converted" pro nome "puro" do arquivo e remover as versões originais (não convertidas?). Outra coisa: É importante só adicionar arquivos que estão sendo usados *agora*, senão acabamos com um monte de arquivos velhos no repo que ninguem usa.

2022-07-17 19:30 UTC, marcopaganini commented on config.toml
>      subtitle = "Tudo que você sempre quis saber sobre Programação de Computadores e nunca teve coragem de perguntar aos seus pais."
Talvez seja o momento de mudar pra "Tudo que você sempre quis saber sobre Programação de Computadores e nunca teve coragem de perguntar" ?

2022-07-17 19:30 UTC, marcopaganini commented on config.toml
> +    text =  "teste"
???

2022-07-17 19:30 UTC, marcopaganini commented on data/carousel/por onde comecar.yaml
> +weight: 3
Arquivos com espaços no nome criam complicação. O ideal é escolher "-" ou "_" pra compor os arquivos (e padronizar no site inteiro, mas isso é mais difícil). Tem vários arquivos com espaços no nome, mas coloquei o comentário apenas no primeiro.

2022-07-17 19:30 UTC, marcopaganini commented on layouts/index.html
> +{{ partial "head.html" . }}
Nit: Alguma razão pra remover os indents?

2022-07-17 19:30 UTC, marcopaganini commented on layouts/index.html
> +</html>
Faltou LF no final do arquivo.

2022-07-17 19:30 UTC, marcopaganini commented on layouts/partials/carousel.html
> +{{ end }}
Faltou LF no final do arquivo.

2022-07-20 02:54 UTC, mpinheir commented on config.toml
>      subtitle = "Tudo que você sempre quis saber sobre Programação de Computadores e nunca teve coragem de perguntar aos seus pais."
Done

2022-07-20 03:02 UTC, mpinheir commented on layouts/index.html
> +{{ partial "head.html" . }}
Coisas do Visual Studio Code

2022-07-21 02:10 UTC, mpinheir commented on data/carousel/por onde comecar.yaml
> +weight: 3
resolved.

2022-07-25 07:26 UTC, marcopaganini reviewed
As mudanças ficaram OK (mas não entendi porque voce teve que quebrar o `if` no template em três separados, mas isso não é um grande problema).

Antes de submeter, acho que seria uma boa idéia eliminar do PR as imagens que a gente não está usando (como as do carousel) pra evitar crescimento excessivo do repo.

Uma vez mergeado, o repo nunca baixa de tamanho.

2022-07-28 03:54 UTC, merged