Adcionando artigo "Conectando replit ao github"
OsProgramadores/op-website-hugo pull request #845
Opened 2023-09-19 10:40 UTC by ValdineiJunior

2023-09-19 18:04 UTC, marcopaganini requested changes
Mais um detalhe: Se puder, verifique se é possível reduzir o tamanho da imagem. Existem várias ferramentas online pra isso.

2023-09-19 18:04 UTC, marcopaganini commented on content/blog/conectando-replit-ao-github.md
> +Quando solicitado, pressione "Enter" para aceitar o local padrão para salvar a chave. Você também pode definir uma senha para a chave, mas isso é opcional.
Isso é uma PÉSSIMA idéia por várias razões.

Primeiro, voce está criando uma chave privada num servidor onde não controla. Basicamente, qualquer um que tenha acesso a isso (quem sabe quem tem?) ganha acesso total ao seu repo.

Segundo é que o uso de SSH **sem senha** é totalmente desrecomendado.

O problema aqui é que pode não haver uma outra solução, já que o replit não aceita SSH. Se aceitasse, seria possível usar agent forwarding e manter a chave na sua estação.

Talvez uma opção seja explicar que isso é um risco e que essa chave só deverá ser usada para este repo em particular. E sempre colocar uma passphrase forte nela.

2023-09-19 18:38 UTC, ValdineiJunior commented on PARTICIPANTES.md
> -| Abraão Nascimento Carvalho     | abraaocrvlhodev@gmail.com               | https://github.com/abraaocrvlhodev        |
$ git pull -r upstream master
From https://github.com/OsProgramadores/op-website-hugo
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.

Será que estou fazendo algo errado ? até percebi que minha PR retirou mas não atualiza por esse comando.

2023-09-19 19:35 UTC, ValdineiJunior commented on content/blog/conectando-replit-ao-github.md
> +Quando solicitado, pressione "Enter" para aceitar o local padrão para salvar a chave. Você também pode definir uma senha para a chave, mas isso é opcional.
Entendido, fiz uma alteração neste sentido.

2023-09-19 19:49 UTC, ValdineiJunior commented on content/blog/conectando-replit-ao-github.md
> +Passo 5: Configure sua Conta Git, na aba Console, localizada à direita da interface, execute os seguintes comandos para configurar sua conta Git:
Alterado passo 5 para retirada da redundancia.

2023-09-21 22:10 UTC, ValdineiJunior commented on PARTICIPANTES.md
> -| Abraão Nascimento Carvalho     | abraaocrvlhodev@gmail.com               | https://github.com/abraaocrvlhodev        |
Me parece que meu fork lá no github estava desatualizado, sincronizei ele.
E utilizei git reset --hard upstream/master pra voltar para master, e adcionei novamente os arquivos.
Não sei se seira o correto, mas resolveu o problema.

2023-10-06 03:14 UTC, marcopaganini approved these changes

2023-10-06 03:14 UTC, marcopaganini commented
Desculpe a demora. Andei ocupado e acabei esquecendo da sua PR! :fearful:

2023-10-06 03:15 UTC, merged

2023-10-06 13:00 UTC, ValdineiJunior commented
Tranquilo, obrigado pela atenção !