Inclusão de participante: adijanio.
OsProgramadores/op-website-hugo pull request #876
Opened 2024-03-13 02:44 UTC by Adijanyo

Solicitação para adicionar participante: Adijanyo Tavares
#1: Git Básico

2024-03-13 03:12 UTC, mpinheir commented
@Adijanyo deu erro pois você não colocou o nome em ordem alfabética. Corriga por favor.

2024-03-15 01:49 UTC, magnussolidus approved these changes
LGTM!

2024-03-15 01:59 UTC, Adijanyo commented
Desculpe, não entendi o que é LGTM?

2024-03-15 03:30 UTC, mpinheir commented
@Adijanyo LGTM = Looks Good To Me. Prache os Devs que revisam PR para indicar que o PR está ok.

2024-03-15 03:31 UTC, mpinheir reviewed
@Adijanyo você só deve adicionar sua linha e não modificar a kinha acima da sua. Retifique por favor.

2024-03-15 03:31 UTC, Adijanyo commented
Obrigado

2024-03-15 14:27 UTC, magnussolidus requested changes
Por favor, faça o ajuste conforme o @mpinheir lhe orientou.

2024-03-15 14:27 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Adilson Boson Almeida Junior   | adboson@gmail.com                       | https://github.com/adboson                |
Reverta esta alteração, você não precisa mexer em outras linhas além da que adiciona o próprio nome.

2024-03-16 05:48 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Adilson Boson Almeida Junior   | adboson@gmail.com                       | https://github.com/adboson                |
@Adijanyo Você precisa ajustar o arquivo para ter somente a adição dos seus dados sem interferir nos demais.

2024-04-03 02:19 UTC, closed without merging