Inclusao de participante: Davi Santos Santana
OsProgramadores/op-website-hugo pull request #938
Opened 2024-10-11 13:49 UTC by DaviSantanaS

2024-10-11 16:36 UTC, magnussolidus requested changes
Seu PR não deve ter outras alterações, salvo a adição do seu nome à lista.

2024-10-13 20:08 UTC, magnussolidus requested changes

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Anderson Unsonst               | andersonunsonst@gmail.com               | https://github.com/andersonunsonst        |
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +- Adicione o seu nome, email e página do github na lista abaixo.
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +- A lista é ordenada por _nome_, seguida de _prenome_ e _sobrenome_.
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +- Emails inválidos serão rejeitados automaticamente.
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +- URLs do github deverão ser no formato: `https://github.com/seu_usuario`
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +- Observe o formato utilizado pelas entradas abaixo e mantenha o padrão.
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +- Se necessário, realinhe as barras verticais de todos os nomes se o seu
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Andre Caviuna                  | abaquar.dev@gmail.com                   | https://github.com/Caviuna                |
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Hamon de Córdova Jorge         | hamoncj@gmail.com                       | https://github.com/hamonCordova           |
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Luiza Vitória Costa Linda      | luuhcosta290@gmail.com                  | https://github.com/luiiza0                |
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-13 20:08 UTC, magnussolidus commented on PARTICIPANTES.md
> +| Walliton jose siqueira pereira | Wallitonccb@gmail.com                   | https://github.com/WallitonSiqueira       |
Você não deve realizar alteração nessa linha. Ela nada tem a ver com a adição do seu nome e perfil do github.

2024-10-19 00:40 UTC, mpinheir commented
@DaviSantanaS você pretende resolver os problemas indicados pelo @magnussolidus ou planeja fechar este PR e começar outro?

2024-11-06 02:43 UTC, closed without merging